<template><aside class="project-inspector-pane"><StageTimeline :stages="projection.stages" @history="emit('history',$event)"/><StageActionPanel :actions="projection.allowedActions" @action="emit('action',$event)"/><section class="materials"><header><small>项目资料</small><strong>资料与版本</strong></header><p v-if="!projection.materials.length">项目资料发布后会归档在这里。</p><a v-for="item in projection.materials" :key="item.id" :href="item.downloadUrl || undefined" :target="item.downloadUrl ? '_blank' : undefined"><span>{{ item.category }}</span><strong>{{ item.name }}</strong><small>{{ item.version == null ? '等待版本' : `版本 ${item.version}` }}</small></a></section><section class="project-facts"><small>项目信息</small><dl><div><dt>项目状态</dt><dd>{{ statusText }}</dd></div><div><dt>最近更新</dt><dd>{{ dateText(projection.project.updatedAt) }}</dd></div></dl></section></aside></template>
<script setup lang="ts">
import { computed } from 'vue'
import type { ProjectAllowedAction, ProjectWorkspaceProjection } from '@/modules/project/types'
import StageTimeline from './StageTimeline.vue'
import StageActionPanel from './StageActionPanel.vue'
const props=defineProps<{projection:ProjectWorkspaceProjection}>();const emit=defineEmits<{history:[id:number];action:[action:ProjectAllowedAction]}>()
const statusText=computed(()=>({ACTIVE:'进行中',PAUSED:'已暂停',COMPLETED:'已完成',TERMINATED:'已终止'} as Record<string,string>)[props.projection.project.status]||'处理中')
function dateText(value:string|null){return value?value.replace('T',' ').slice(0,16):'等待更新'}
</script>
<style scoped>.project-inspector-pane{min-height:0;padding:23px 20px;border-left:1px solid #dde0dc;background:#fafbf9;overflow:auto}.materials{padding:18px 0;border-bottom:1px solid #e5e7e3}.materials header{margin-bottom:10px;display:grid;gap:2px}.materials header small,.project-facts>small{color:#9b632f;font-size:9px;font-weight:750;letter-spacing:.08em}.materials header strong{font-size:13px}.materials>p{margin:0;color:#7c817d;font-size:9px;line-height:1.6}.materials>a{padding:8px 0;border-top:1px solid #e7e9e5;display:grid;grid-template-columns:1fr auto;gap:2px;color:inherit;text-decoration:none}.materials>a span{grid-column:1/-1;color:#8a908b;font-size:8px}.materials>a strong{font-size:10px}.materials>a small{color:#8b5b31;font-size:9px}.project-facts{padding-top:18px}.project-facts dl{margin:8px 0 0}.project-facts dl div{padding:8px 0;border-top:1px solid #e7e9e5;display:flex;justify-content:space-between}.project-facts dt{color:#858b86;font-size:9px}.project-facts dd{margin:0;font-size:10px;font-weight:650}</style>