<template>
  <section class="stage-timeline"><header><small>七阶段服务</small><strong>项目进度</strong></header><ol><li v-for="stage in stages" :key="stage.id" :class="stageClass(stage)"><button type="button" @click="select(stage)"><span>{{ stage.sortOrder }}</span><div><strong>{{ stage.stageName }}</strong><small>{{ stageStatus(stage.status) }}</small></div></button><div v-if="expanded === stage.id" class="stage-history"><p v-if="!stage.histories">正在读取阶段记录…</p><p v-else-if="!stage.histories.length">此阶段暂无历史记录。</p><article v-for="event in stage.histories || []" :key="event.id"><time>{{ dateText(event.occurredAt) }}</time><span>{{ historyText(event) }}</span></article></div></li></ol></section>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import type { ProjectStage, ProjectStageHistory } from '@/modules/project/types'
defineProps<{ stages: ProjectStage[] }>()
const emit = defineEmits<{ history: [stageId: number] }>()
const expanded = ref<number | null>(null)
function select(stage: ProjectStage) { expanded.value = expanded.value === stage.id ? null : stage.id; if (expanded.value) emit('history', stage.id) }
function stageClass(stage: ProjectStage) { return { current: ['ACTIVE', 'WAITING_CUSTOMER', 'PROCESSING', 'UNDER_REVIEW', 'CHANGE_PROCESSING', 'SUSPENDED'].includes(stage.status), completed: stage.status === 'COMPLETED' } }
function stageStatus(status: string) { return ({ NOT_STARTED: '待开始', ACTIVE: '进行中', WAITING_CUSTOMER: '等待您的反馈', PROCESSING: '服务团队处理中', UNDER_REVIEW: '审核中', CHANGE_PROCESSING: '修改处理中', COMPLETED: '已完成', SUSPENDED: '已暂停' } as Record<string,string>)[status] || '状态已更新' }
function dateText(value: string) { return value ? value.replace('T',' ').slice(5,16) : '' }
function historyText(event: ProjectStageHistory) { if (event.reason) return event.reason; return ({ ACTIVATED: '阶段已开始', PROCESSING: '已进入处理', WAITING: '正在等待您的反馈', REVIEW_REQUESTED: '已进入审核', COMPLETED: '阶段已完成', REOPENED: '阶段已重新开启', SUSPENDED: '阶段已暂停', RESUMED: '阶段已恢复' } as Record<string,string>)[event.eventType] || '阶段记录已更新' }
</script>
<style scoped>
.stage-timeline{padding-bottom:20px;border-bottom:1px solid #e5e7e3}.stage-timeline header{margin-bottom:15px;display:grid;gap:2px}.stage-timeline header small{color:#9b632f;font-size:9px;font-weight:750;letter-spacing:.08em}.stage-timeline header strong{font-size:14px}.stage-timeline ol{margin:0;padding:0;list-style:none}.stage-timeline li{position:relative}.stage-timeline li:not(:last-child):before{content:"";position:absolute;left:11px;top:28px;bottom:-5px;width:1px;background:#dfe2dd}.stage-timeline li.completed:not(:last-child):before{background:#789a85}.stage-timeline li>button{width:100%;padding:6px 0;border:0;background:transparent;display:flex;align-items:center;gap:10px;text-align:left;cursor:pointer}.stage-timeline li>button>span{width:23px;height:23px;z-index:1;border:1px solid #d8dcd7;border-radius:50%;display:grid;place-items:center;background:#fafbf9;color:#8a908b;font-size:9px}.stage-timeline li.current>button>span{border-color:#a36a37;background:#fff6eb;color:#8b5728}.stage-timeline li.completed>button>span{border-color:#789a85;background:#789a85;color:#fff}.stage-timeline li>button div{display:grid;gap:1px}.stage-timeline li>button strong{font-size:11px}.stage-timeline li>button small{color:#8c928d;font-size:9px}.stage-history{margin:3px 0 6px 33px;padding:7px 9px;border-left:2px solid #d7c2ab;background:#f7f7f4}.stage-history p,.stage-history article{margin:0;color:#747b76;font-size:9px;line-height:1.6}.stage-history article{display:grid;grid-template-columns:70px 1fr;gap:5px}.stage-history time{color:#a0a49f}
</style>
